@REM
@REM regulate.path.cmd
@REM

@REM ％* で指定されたパスの絶対パスを %LIBCMD_REGULATE_PATH% に格納する。


@REM
@REM 準備
@REM

@SET LIBCMD_REGULATE_PATH_ECHO=@
@IF /I "/?" EQU "%1" GOTO SHOW_HELP
@IF /I "/echo" EQU "%1" GOTO ECHO_ON
@GOTO BODY

:ECHO_ON
@SHIFT
@SET LIBCMD_REGULATE_PATH_ECHO=
@GOTO BODY


@REM
@REM 処理本体
@REM

:BODY
%LIBCMD_REGULATE_PATH_ECHO%SET LIBCMD_REGULATE_PATH=%~dpnx1
%LIBCMD_REGULATE_PATH_ECHO%SET LIBCMD_REGULATE_PATH_STRICT="%~dpnx1"
:LOOP
@SHIFT
@IF /I "" EQU "%~dpnx1" GOTO :EOF
%LIBCMD_REGULATE_PATH_ECHO%SET LIBCMD_REGULATE_PATH=%LIBCMD_REGULATE_PATH% %~dpnx1
%LIBCMD_REGULATE_PATH_ECHO%SET LIBCMD_REGULATE_PATH_STRICT=%LIBCMD_REGULATE_PATH_STRICT% "%~dpnx1"
@GOTO LOOP


@REM
@REM ヘルプ表示
@REM

:SHOW_HELP
@ECHO コマンドライン引数で指定されたパスの絶対パスを環境変数LIBCMD_REGULATE_PATHにセットします。
@ECHO.
@ECHO %~n0[%~x0] [/echo] [絶対パスを取得したいパスの引数列]
@ECHO.
@ECHO /echo   標準出力にechoしながら実行します。
@GOTO :EOF
