@REM
@REM スナップショットの作成
@REM

@REM
@REM 親ディレクトリの作成
@REM

@SET SOLOMON_MAKE_SNAMPSHOT_DEST=%~dpnx2%SOLOMON_SNAPSHOT_HISTORY_DIR%
@IF NOT EXIST "%SOLOMON_MAKE_SNAMPSHOT_DEST%\.." CALL "%SOLOMON_LIBCMD_DIR%\mkdir.ex.cmd" "%SOLOMON_MAKE_SNAMPSHOT_DEST%\.."


@REM
@REM スナップショットの作成
@REM

@IF /I ".zip" EQU "%SOLOMON_MAKE_SNAMPSHOT_DEST:~-4%" CALL "%~dp0zip.dir.cmd" "%~dpnx1" "%SOLOMON_MAKE_SNAMPSHOT_DEST%"&GOTO MAKE_SNAPSHOT_END
@CALL "%~dp0mirror.dir.cmd" "%~dpnx1" "%SOLOMON_MAKE_SNAMPSHOT_DEST%"
:MAKE_SNAPSHOT_END


@REM
@REM 最終日ディレクトリへのショートカットファイル作成
@REM

@IF /I "" EQU "%SOLOMON_SNAPSHOT_HISTORY_DIR%" GOTO :EOF
@SET SOLOMON_MAKE_HISTORY_SHORTCUT_FILE_PATH=%~dpnx2\%SOLOMON_SNAPSHOT_HISTORY_SHORTCUT_NAME%.lnk
@SET SOLOMON_MAKE_HISTORY_SHORTCUT_TARGET_PATH=%SOLOMON_MAKE_SNAMPSHOT_DEST%\..\
@DEL "%SOLOMON_MAKE_HISTORY_SHORTCUT_FILE_PATH%" >NUL 2>NUL
@CALL "%SOLOMON_LIBCMD_DIR%\make.lnk.cmd" "%SOLOMON_MAKE_HISTORY_SHORTCUT_TARGET_PATH%" "%SOLOMON_MAKE_HISTORY_SHORTCUT_FILE_PATH%"
