@REM
@REM ステータスの保存
@REM

@IF NOT EXIST "%SOLOMON_BUILD_STATUS_CMD%\.." CALL "%SOLOMON_LIBCMD_DIR%\mkdir.ex.cmd" "%SOLOMON_BUILD_STATUS_CMD%\.."
@TYPE NUL >"%SOLOMON_BUILD_STATUS_CMD%"
@ECHO @SET SOLOMON_PREVIOUS_TEST_FAILED_BUILD_LIST=%SOLOMON_PREVIOUS_TEST_FAILED_BUILD_LIST%>>"%SOLOMON_BUILD_STATUS_CMD%"
@ECHO @SET SOLOMON_PREVIOUS_COMPILE_FAILED_BUILD_LIST=%SOLOMON_PREVIOUS_COMPILE_FAILED_BUILD_LIST%>>"%SOLOMON_BUILD_STATUS_CMD%"
@ECHO @SET SOLOMON_PREVIOUS_COMPILE_WARNED_BUILD_LIST=%SOLOMON_PREVIOUS_COMPILE_WARNED_BUILD_LIST%>>"%SOLOMON_BUILD_STATUS_CMD%"
