@REM
@REM 更新が確認されるまで待機
@REM

@ECHO %SOLOMON_MESSAGE_PREFIX%監視ディレクトリ %SOLOMON_TARGET_DIR% が更新が検出されるまで待機

@REM 監視ループ
:AUTO_BUILD_POLLING

@REM 監視ディレクトリ内(サブディレクトリを含む)の更新日時付きのファイル一覧の取得
@CALL "%SOLOMON_SUBCMD_DIR%\make.dir.signature.cmd" "%SOLOMON_TARGET_DIR%" "%SOLOMON_AUTO_BUILD_CURRENT_DIR_TXT%"

@REM 前回のコンパイル時 監視ディレクトリ内(サブディレクトリを含む)の更新日時付きのファイル一覧
@FC "%SOLOMON_AUTO_BUILD_PREVIOUS_DIR_TXT%" "%SOLOMON_AUTO_BUILD_CURRENT_DIR_TXT%" >NUL

@REM 変わっていなければ %SOLOMON_AUTO_BUILD_POLLING_INTERVAL% 秒待機後に再度確認する
@IF "0" EQU "%ERRORLEVEL%" CALL "%SOLOMON_LIBCMD_DIR%\sleep.cmd" %SOLOMON_AUTO_BUILD_POLLING_INTERVAL%&GOTO AUTO_BUILD_POLLING

@REM 変わっていれば %SOLOMON_AUTO_BUILD_DELAY% 秒待機後にこのバッチファイルを抜ける
@IF /I "TRUE" EQU "%SOLOMON_AUTO_BUILD_WITH_CLS%" CLS
@ECHO %SOLOMON_MESSAGE_PREFIX%監視ディレクトリ %SOLOMON_TARGET_DIR% の更新を検出！
@CALL "%SOLOMON_LIBCMD_DIR%\sleep.cmd" %SOLOMON_AUTO_BUILD_DELAY%
